apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: Opaque
stringData:
  password: o6MhRttKLM

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-username
type: Opaque
stringData:
  username: root
